Create cancel ticket
maivuhoa/SATTDN0203-MAIVUHOA pull request #5
Opened 2022-11-17 10:04 UTC by maivuhoa

2022-11-22 03:37 UTC, MinhQuan119 requested changes

2022-11-22 03:37 UTC, MinhQuan119 commented on src/RailWay/java/Common/constant/SeatType.java
> +package Common.constant;
Cái này là data, nên để trong DataObjects

2022-11-22 03:37 UTC, MinhQuan119 commented on src/RailWay/java/Common/constant/Station.java
> +package Common.constant;
Tương tự seatType

2022-11-22 03:37 UTC, MinhQuan119 commented on src/RailWay/java/Common/utilities/Utilities.java
> +
Xóa dòng trống dư trong hàm

2022-11-22 03:37 UTC, MinhQuan119 commented on src/RailWay/java/PageObjects/BookTicketPage.java
> +        return Constant.WEBDRIVER.findElement(By.xpath(strXPathSelectDropdown + elementName + "']"));
TIm hiểu về String.format với %s, ko dùng nối String như này

2022-11-22 03:37 UTC, MinhQuan119 commented on src/RailWay/java/PageObjects/BookTicketPage.java
> +        logger.info("Navigate to QA Railway Website");
Log step để ở test case thay vì method

2022-11-22 03:37 UTC, MinhQuan119 commented on src/RailWay/java/PageObjects/GeneralPage.java
>          this.getTabRegister().click();
không cần dùng this, tương tự cho các method và các page khác

2022-11-22 03:37 UTC, MinhQuan119 commented on src/RailWay/java/PageObjects/HomePage.java
> +    private final By lblWellComeRailWay = By.xpath("//div[@id='content']/h1[text()='Welcome to Safe Railway']");
lỗi chính tả WellCome

2022-11-22 03:37 UTC, MinhQuan119 commented on src/RailWay/java/PageObjects/BookTicketPage.java
> +    public WebElement getElementBtnBookTicket() {
vì sao phải tạo 1 hàm để gọi lại getBtnBookTicket, sao ko dùng trực tiếp getBtnBookTicket lun

2022-11-22 03:37 UTC, MinhQuan119 commented on src/RailWay/java/PageObjects/MyTicketPage.java
> +
Xóa dòng trống

2022-11-22 03:37 UTC, MinhQuan119 commented on src/RailWay/java/PageObjects/RegisterPage.java
> +    public void testRegister(String UserName, String Password, String ConfirmPassword, String PID) {
method làm chức năng register, chữ test dư thừa

2022-11-22 03:37 UTC, MinhQuan119 commented on src/RailWay/java/PageObjects/TimeTablePage.java
> +        return Constant.WEBDRIVER.findElement(By.xpath("//table[@class='MyTable WideTable']//td[count(//th[text()=" + "'" + value + "'" + "]/preceding-sibling::th)+1]"));
tạo biến String cho xpath, xong gọi biến ở đây, ko dùng trực tiếp

2022-11-22 03:37 UTC, MinhQuan119 commented on src/RailWay/java/PageObjects/TimeTablePage.java
> +
check lại format, nhiều trường hợp trong method chừa row trống quá

2022-11-22 03:37 UTC, MinhQuan119 commented on src/RailWay/java/TestCases/BaseTest.java
> +    public void registerNewAccount() {
Vì sao ko để hàm này trong RegisterPage mà lại để ở đây?

2022-11-22 03:37 UTC, MinhQuan119 commented on src/RailWay/java/TestCases/BaseTest.java
> +    public Object[][] ValidEmaillength() {
check lại naming convention

2022-11-22 03:37 UTC, MinhQuan119 commented on src/RailWay/java/TestCases/bookTicket/BookTicketSuccess.java
> +        System.out.println("TC14- User can book 1 ticket at a time");
xóa dòng sout này, nghiên cứu sử dụng description của @test

2022-11-22 03:37 UTC, MinhQuan119 commented on src/RailWay/java/TestCases/bookTicket/BookTicketViaTimeTable.java
> +        Utilities.scrollIntoView(bookTicketPage.getElementBtnBookTicket());
dùng trong method, ko gọi trực tiếp element ra ngoài testcase

2022-11-22 07:45 UTC, maivuhoa commented on src/RailWay/java/Common/utilities/Utilities.java
> +
dạ done anh

2022-11-22 07:45 UTC, maivuhoa commented on src/RailWay/java/PageObjects/BookTicketPage.java
> +        return Constant.WEBDRIVER.findElement(By.xpath(strXPathSelectDropdown + elementName + "']"));
dạ done anh

2022-11-22 08:05 UTC, maivuhoa commented on src/RailWay/java/PageObjects/BookTicketPage.java
> +        logger.info("Navigate to QA Railway Website");
dạ done anh

2022-11-22 08:11 UTC, maivuhoa commented on src/RailWay/java/PageObjects/TimeTablePage.java
> +
dạ done anh

2022-11-22 08:19 UTC, maivuhoa commented on src/RailWay/java/TestCases/BaseTest.java
> +    public void registerNewAccount() {
dạ em đã chuyển hàm này qua RegisterPage

2022-11-22 08:25 UTC, maivuhoa commented on src/RailWay/java/TestCases/BaseTest.java
> +    public Object[][] ValidEmaillength() {
dạ done anh

2022-11-22 09:08 UTC, maivuhoa commented on src/RailWay/java/TestCases/bookTicket/BookTicketViaTimeTable.java
> +        Utilities.scrollIntoView(bookTicketPage.getElementBtnBookTicket());
dạ done anh

2022-11-22 09:21 UTC, maivuhoa commented on src/RailWay/java/TestCases/bookTicket/BookTicketSuccess.java
> +        System.out.println("TC14- User can book 1 ticket at a time");
dạ em đang research thêm Extent Report

2022-11-23 02:39 UTC, maivuhoa commented on src/RailWay/java/PageObjects/BookTicketPage.java
> +    public WebElement getElementBtnBookTicket() {
dạ done anh

2022-11-23 02:39 UTC, maivuhoa commented on src/RailWay/java/PageObjects/GeneralPage.java
>          this.getTabRegister().click();
dạ done anh

2022-11-23 08:34 UTC, maivuhoa commented on src/RailWay/java/Common/constant/SeatType.java
> +package Common.constant;
dạ done anh

2022-11-24 08:09 UTC, MinhQuan119 approved these changes

2022-11-24 08:15 UTC, merged